name: CloudFlare-Main

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true

  build:
    name: Hugo Build
    needs: checkout
    uses: monamimani-sites/emmanuelthivierge/.github/workflows/BuildHugo.yml@1

  # deploy:
  #   name: Deploy to Cloudflare
  #   needs: build
  #   runs-on: ubuntu-latest
      
  #   steps:
  #     - name: Publish to Cloudflare Pages
  #       uses: cloudflare/pages-action@1
  #       with:
  #         apiToken: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
  #         accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #         gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  #         projectName: "emmanuelthivierge"
  #         directory: "_build"
  #         branch: "dev"
