name: CloudFlare-Main

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build using Hugo and Deploy to Cloudflare
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      
      - name: Hugo Build
        uses: monamimani-sites/emmanuelthivierge/.github/workflows/BuildHugo.yml@v1

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: "emmanuelthivierge"
          directory: "_build"
          branch: "dev"
