name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build using Hugo and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: true
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Cache hugo modules
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        run: hugo --destination="_build" --minify --cleanDestinationDir

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          wait-on: http://localhost:1313
          browser: chrome